baseURL = 'https://aiether.info/'
locale = 'en'
title = 'Aiether — Texas Government Accountability'
theme = 'congo'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
