[[main]]
  name = "Articles"
  url = "/posts/"
  weight = 10

[[main]]
  name = "Civil Rights"
  url = "/categories/civil-rights/"
  weight = 12

[[main]]
  name = "Corruption Watch"
  url = "/corruption-watch/"
  weight = 15

[[main]]
  name = "Colorado County"
  url = "/categories/colorado-county/"
  weight = 20

[[main]]
  name = "Matagorda County"
  url = "/categories/matagorda-county/"
  weight = 25

[[main]]
  name = "All TPIA Records"
  url = "/categories/tpia-records/"
  weight = 30
