[[main]]
  name = "Articles"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Colorado County"
  url = "/categories/colorado-county/"
  weight = 20

[[main]]
  name = "TPIA Records"
  url = "/categories/tpia-records/"
  weight = 30
